using System.Runtime.InteropServices;
using VHSDecode.Core.Tbc;
using Xunit;

namespace VHSDecode.Tests;

public sealed class ApproxCatmullRom4ResamplerTests
{
    [Fact(DisplayName = "Approx Catmull-Rom4 matches known knots and midpoint")]
    public void MatchesKnownKnotsAndMidpoint()
    {
        double[] source = [0.0, 1.0, 4.0, 9.0, 16.0];

        Assert.Equal(1.0f, ApproxCatmullRom4Resampler.Sample(source, 1.0));
        Assert.Equal(2.25f, ApproxCatmullRom4Resampler.Sample(source, 1.5));
        Assert.Equal(4.0f, ApproxCatmullRom4Resampler.Sample(source, 2.0));
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 matches frozen Rust f32/FMA vectors")]
    public void MatchesFrozenRustFloat32Vectors()
    {
        // Generated by tape-decode-rs' scalar catmull_rom4 expression using
        // rustc 1.95.0, -C opt-level=3. Every input and result is stored by f32 bits.
        (uint P0, uint P1, uint P2, uint P3, uint Fraction, uint Level, uint Expected)[] vectors =
        [
            (0x47A52BD0u, 0x48056950u, 0x48CB41F4u, 0xC98F7680u, 0x3F42D100u, 0x3F3BF800u, 0x48A9EEC3u),
            (0x493DDE08u, 0xC964EE16u, 0xC8260438u, 0x48694160u, 0x3F298F00u, 0x3FC9A200u, 0xC93EE893u),
            (0xC9858A17u, 0x49201EA2u, 0x49446504u, 0x47815440u, 0x3F74DD00u, 0x3FB09800u, 0x49899AB7u),
            (0xC95CB6D2u, 0x48C78958u, 0x45ED6A00u, 0x48248D78u, 0x3F0C3B00u, 0x3FD45E00u, 0x48C7F56Au),
            (0xC921C758u, 0x47F288C0u, 0x4984F9DEu, 0xC8AE5D64u, 0x3F3B2900u, 0x40053A00u, 0x49FDB3CAu),
            (0xC93BFB7Eu, 0xC5F67500u, 0xC803E3A8u, 0xC95E6C94u, 0x3D893800u, 0x3F9C5A00u, 0x464FBBBDu),
            (0x483981A0u, 0xC709EF20u, 0x491C64A2u, 0xC9670402u, 0x3E836A00u, 0x3FA79000u, 0x4825C566u),
            (0x48D878A8u, 0x47900520u, 0x48E3BA04u, 0xC98DF85Du, 0x3C8A6000u, 0x3F7B2C00u, 0x478EA232u),
            (0x48A58474u, 0x492392B6u, 0xC992B7C5u, 0x48F8D158u, 0x3F748100u, 0x4001F600u, 0xCA136173u),
            (0x4853C100u, 0xC863DD58u, 0x4990257Eu, 0x493C9A28u, 0x3EE37E00u, 0x400A0900u, 0x49414C02u),
            (0x48191DB8u, 0x49731FE4u, 0x48B7CEE0u, 0xC965FDDAu, 0x3EFF1A00u, 0x3FDB8800u, 0x49AC24FBu),
            (0x47A28150u, 0x498FF31Eu, 0xC944C184u, 0xC86A0328u, 0x3F256B00u, 0x401DE700u, 0xC8C99593u),
            (0x47C351C0u, 0xC8E75F44u, 0xC76B4F40u, 0x496C4162u, 0x3F4ED900u, 0x40153200u, 0xC8DB87B3u),
            (0xC8AE6044u, 0xC90C5BCCu, 0x494917AAu, 0x493C5E38u, 0x3E2D5C00u, 0x40086500u, 0xC9581282u),
            (0xC88DEA80u, 0xC89CA818u, 0x48ABECD4u, 0x47F0D060u, 0x3D665000u, 0x40164000u, 0xC92B8575u),
            (0xC8F2E6F8u, 0x4970D100u, 0x49136CB2u, 0xC8D5B688u, 0x3F4F8300u, 0x3FEF0600u, 0x49A9B2A1u)
        ];

        foreach ((uint p0Bits, uint p1Bits, uint p2Bits, uint p3Bits, uint fractionBits, uint levelBits, uint expectedBits) in vectors)
        {
            float[] floatSource =
            [
                BitConverter.UInt32BitsToSingle(p0Bits),
                BitConverter.UInt32BitsToSingle(p1Bits),
                BitConverter.UInt32BitsToSingle(p2Bits),
                BitConverter.UInt32BitsToSingle(p3Bits),
                0.0f
            ];
            double[] source = Array.ConvertAll(floatSource, static value => (double)value);
            float fraction = BitConverter.UInt32BitsToSingle(fractionBits);
            double[] positions = [1.0 + fraction];
            double[] levels = [BitConverter.UInt32BitsToSingle(levelBits)];
            var floatOutput = new float[1];
            var directFloatOutput = new float[1];
            var doubleOutput = new double[1];

            ApproxCatmullRom4Resampler.Resample(source, positions, levels, floatOutput);
            ApproxCatmullRom4Resampler.Resample(floatSource, positions, levels, directFloatOutput);
            ApproxCatmullRom4Resampler.Resample(source, positions, levels, doubleOutput);

            Assert.Equal(expectedBits, BitConverter.SingleToUInt32Bits(floatOutput[0]));
            Assert.Equal(expectedBits, BitConverter.SingleToUInt32Bits(directFloatOutput[0]));
            Assert.Equal(expectedBits, BitConverter.SingleToUInt32Bits((float)doubleOutput[0]));
            Assert.Equal((double)floatOutput[0], doubleOutput[0]);
        }
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 f32 source matches exact widening for every output shape")]
    public void Float32SourceMatchesExactWideningForEveryOutputShape()
    {
        float[] floatSource = Enumerable.Range(0, 257)
            .Select(index => (float)((1_000_000.0 * Math.Sin(index * 0.071)) + (17.0 * index)))
            .ToArray();
        double[] widenedSource = Array.ConvertAll(floatSource, static value => (double)value);
        double[] positions = Enumerable.Range(0, 1_024)
            .Select(index => 0.5 + ((floatSource.Length - 2.0) * index / 1_023.0))
            .ToArray();
        positions[0] = double.NaN;
        positions[1] = double.NegativeInfinity;
        positions[^1] = double.PositiveInfinity;
        double[] levels = Enumerable.Range(0, positions.Length)
            .Select(index => 0.75 + (0.5 * ((index % 29) / 28.0)))
            .ToArray();
        const double SourcePositionShift = -0.3125;

        var expectedFloat = new float[positions.Length];
        var actualFloat = new float[positions.Length];
        ApproxCatmullRom4Resampler.Resample(
            widenedSource,
            positions,
            levels,
            SourcePositionShift,
            expectedFloat);
        ApproxCatmullRom4Resampler.Resample(
            floatSource,
            positions,
            levels,
            SourcePositionShift,
            actualFloat);
        Assert.True(
            MemoryMarshal.AsBytes(expectedFloat.AsSpan()).SequenceEqual(
                MemoryMarshal.AsBytes(actualFloat.AsSpan())),
            "Direct f32-source output differed from the same samples exactly widened to double.");

        var expectedDouble = new double[positions.Length];
        var actualDouble = new double[positions.Length];
        ApproxCatmullRom4Resampler.Resample(
            widenedSource,
            positions,
            levels,
            SourcePositionShift,
            expectedDouble);
        ApproxCatmullRom4Resampler.Resample(
            floatSource,
            positions,
            levels,
            SourcePositionShift,
            actualDouble);
        Assert.Equal(expectedDouble, actualDouble);

        var converter = new VideoOutputConverter(
            ire0: 4_000_000.25,
            hzIre: 100_000.125,
            outputZero: 256,
            vsyncIre: -40.0,
            outputScale: 512.25);
        var expectedUInt16 = new ushort[positions.Length];
        var actualUInt16 = new ushort[positions.Length];
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            widenedSource,
            positions,
            levels,
            SourcePositionShift,
            converter,
            expectedUInt16);
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            floatSource,
            positions,
            levels,
            SourcePositionShift,
            converter,
            actualUInt16);
        Assert.Equal(expectedUInt16, actualUInt16);

        foreach (double position in positions)
        {
            Assert.Equal(
                BitConverter.SingleToUInt32Bits(
                    ApproxCatmullRom4Resampler.Sample(widenedSource, position)),
                BitConverter.SingleToUInt32Bits(
                    ApproxCatmullRom4Resampler.Sample(floatSource, position)));
        }
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 f32 source output is bit-deterministic")]
    public void Float32SourceOutputIsBitDeterministic()
    {
        float[] source = Enumerable.Range(0, 257)
            .Select(index => (float)((1_000_000.0 * Math.Sin(index * 0.071)) + (17.0 * index)))
            .ToArray();
        double[] positions = Enumerable.Range(0, 1_024)
            .Select(index => 1.0 + ((source.Length - 4.0) * index / 1_023.0))
            .ToArray();
        double[] levels = Enumerable.Range(0, positions.Length)
            .Select(index => 0.75 + (0.5 * ((index % 29) / 28.0)))
            .ToArray();
        var expected = new float[positions.Length];
        var actual = new float[positions.Length];
        ApproxCatmullRom4Resampler.Resample(source, positions, levels, 0.1875, expected);

        for (int iteration = 0; iteration < 32; iteration++)
        {
            actual.AsSpan().Fill(float.NaN);
            ApproxCatmullRom4Resampler.Resample(source, positions, levels, 0.1875, actual);
            Assert.True(
                MemoryMarshal.AsBytes(expected.AsSpan()).SequenceEqual(MemoryMarshal.AsBytes(actual.AsSpan())),
                $"Iteration {iteration} differed from the first direct f32-source result.");
        }
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 clamps every four-tap window safely")]
    public void ClampsEveryFourTapWindowSafely()
    {
        double[] source = [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0];
        double[] positions =
        [
            double.NaN,
            double.NegativeInfinity,
            -100.0,
            0.999,
            1.0,
            5.0,
            5.001,
            100.0,
            double.PositiveInfinity
        ];
        double[] levels = Enumerable.Repeat(1.0, positions.Length).ToArray();
        var output = new float[positions.Length];

        ApproxCatmullRom4Resampler.Resample(source, positions, levels, output);

        Assert.Equal([20.0f, 20.0f, 20.0f, 20.0f, 20.0f, 60.0f, 60.0f, 60.0f, 60.0f], output);
        Assert.Equal(20.0f, ApproxCatmullRom4Resampler.Sample(source, double.NaN));
        Assert.Equal(60.0f, ApproxCatmullRom4Resampler.Sample(source, double.PositiveInfinity));
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 direct UInt16 output matches widened f32 conversion")]
    public void DirectUInt16OutputMatchesWidenedFloat32Conversion()
    {
        double[] source = Enumerable.Range(0, 40)
            .Select(index => 4_000_000.0 + (500_000.0 * Math.Sin(index * 0.31)))
            .ToArray();
        double[] positions = Enumerable.Range(0, 64)
            .Select(index => 1.0 + ((source.Length - 4.0) * index / 63.0))
            .ToArray();
        double[] levels = Enumerable.Range(0, positions.Length)
            .Select(index => 0.9 + (index * 0.0025))
            .ToArray();
        var converter = new VideoOutputConverter(
            ire0: 4_000_000.25,
            hzIre: 100_000.125,
            outputZero: 256,
            vsyncIre: -40.0,
            outputScale: 512.25);
        var floatOutput = new float[positions.Length];
        var expected = new ushort[positions.Length];
        var actual = new ushort[positions.Length];

        ApproxCatmullRom4Resampler.Resample(source, positions, levels, floatOutput);
        for (int index = 0; index < expected.Length; index++)
        {
            expected[index] = converter.ConvertHz(floatOutput[index]);
        }

        ApproxCatmullRom4Resampler.ResampleToUInt16(source, positions, levels, converter, actual);

        Assert.Equal(expected, actual);
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 output is deterministic")]
    public void OutputIsDeterministic()
    {
        double[] source = Enumerable.Range(0, 257)
            .Select(index => (1_000_000.0 * Math.Sin(index * 0.071)) + (17.0 * index))
            .ToArray();
        double[] positions = Enumerable.Range(0, 1_024)
            .Select(index => 1.0 + ((source.Length - 4.0) * index / 1_023.0))
            .ToArray();
        double[] levels = Enumerable.Range(0, positions.Length)
            .Select(index => 0.75 + (0.5 * ((index % 29) / 28.0)))
            .ToArray();
        var expected = new float[positions.Length];
        var actual = new float[positions.Length];
        ApproxCatmullRom4Resampler.Resample(source, positions, levels, expected);

        for (int iteration = 0; iteration < 32; iteration++)
        {
            actual.AsSpan().Fill(float.NaN);
            ApproxCatmullRom4Resampler.Resample(source, positions, levels, actual);
            Assert.True(
                MemoryMarshal.AsBytes(expected.AsSpan()).SequenceEqual(MemoryMarshal.AsBytes(actual.AsSpan())),
                $"Iteration {iteration} differed from the first f32 result.");
        }
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 AVX2/FMA output is bit-identical across shapes and tails")]
    public void ForcedVectorMatchesScalarAcrossOutputShapesAndTails()
    {
        if (!ApproxCatmullRom4Resampler.IsVectorizationSupported)
        {
            return;
        }

        double[] doubleSource = Enumerable.Range(0, 521)
            .Select(index =>
                (4_000_000.0 * Math.Sin((index * 0.071) + 0.13)) +
                (123_456.0 * Math.Cos(index * 0.017)) +
                (index * 0.03125))
            .ToArray();
        float[] floatSource = Array.ConvertAll(doubleSource, static value => (float)value);
        int[] outputLengths = [8, 9, 15, 16, 17, 31, 257];
        double[] shifts = [-100.25, -0.3125, 0.0, 0.1875, 123.75];
        var random = new Random(0x4CA7_4D11);

        foreach (int outputLength in outputLengths)
        {
            foreach (double shift in shifts)
            {
                var positions = new double[outputLength];
                var levels = new double[outputLength];
                for (int index = 0; index < outputLength; index++)
                {
                    positions[index] = -16.0 + (random.NextDouble() * (doubleSource.Length + 32.0));
                    levels[index] = -2.0 + (random.NextDouble() * 4.0);
                }

                positions[0] = double.NaN;
                positions[1] = double.NegativeInfinity;
                positions[2] = double.PositiveInfinity;
                positions[3] = 1.0 - shift;
                positions[4] = (doubleSource.Length - 3.0) - shift;
                positions[5] = 0.999_999_999 - shift;
                positions[6] = (doubleSource.Length - 2.999_999_999) - shift;
                levels[0] = -0.0;
                levels[1] = double.Epsilon;
                levels[2] = -double.Epsilon;

                AssertForcedModesMatch(
                    doubleSource,
                    floatSource,
                    positions,
                    levels,
                    shift,
                    $"length={outputLength}, shift={shift:R}");
            }
        }
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 AVX2/FMA preserves non-finite scalar behavior bit-for-bit")]
    public void ForcedVectorMatchesScalarForNonFiniteInputs()
    {
        if (!ApproxCatmullRom4Resampler.IsVectorizationSupported)
        {
            return;
        }

        double[] doubleSource = Enumerable.Range(0, 48)
            .Select(index => 1_000_000.0 * Math.Sin((index * 0.23) + 0.1))
            .ToArray();
        doubleSource[3] = BitConverter.Int64BitsToDouble(unchecked((long)0x7FF8_1234_5678_9ABCul));
        doubleSource[11] = double.PositiveInfinity;
        doubleSource[19] = double.NegativeInfinity;
        doubleSource[27] = double.MaxValue;
        float[] floatSource = Array.ConvertAll(doubleSource, static value => (float)value);
        floatSource[3] = BitConverter.UInt32BitsToSingle(0x7FC1_2345u);
        floatSource[11] = float.PositiveInfinity;
        floatSource[19] = float.NegativeInfinity;
        floatSource[27] = float.MaxValue;

        double[] positions = Enumerable.Range(0, 25)
            .Select(index => 1.0 + ((doubleSource.Length - 4.0) * index / 24.0))
            .ToArray();
        positions[0] = double.NaN;
        positions[1] = double.NegativeInfinity;
        positions[2] = double.PositiveInfinity;
        double[] levels = Enumerable.Range(0, positions.Length)
            .Select(index => 0.75 + (index * 0.03125))
            .ToArray();
        levels[4] = BitConverter.Int64BitsToDouble(unchecked((long)0x7FF8_ABCD_0123_4567ul));
        levels[9] = double.PositiveInfinity;
        levels[14] = double.NegativeInfinity;
        levels[20] = double.MaxValue;

        AssertForcedModesMatch(
            doubleSource,
            floatSource,
            positions,
            levels,
            sourcePositionShift: -0.1875,
            "non-finite source and level lanes");
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 forced vector mode preserves overlapping-span scalar semantics")]
    public void ForcedVectorPreservesOverlappingSpanSemantics()
    {
        if (!ApproxCatmullRom4Resampler.IsVectorizationSupported)
        {
            return;
        }

        const int OutputLength = 17;
        double[] positions = Enumerable.Range(0, OutputLength)
            .Select(index => 1.0 + (27.0 * index / (OutputLength - 1.0)))
            .ToArray();
        double[] levels = Enumerable.Range(0, OutputLength)
            .Select(index => 0.8 + (index * 0.0125))
            .ToArray();

        double[] expectedDoubleBacking = Enumerable.Range(0, 48)
            .Select(index => 2_000_000.0 + (100_000.0 * Math.Sin(index * 0.19)))
            .ToArray();
        double[] actualDoubleBacking = (double[])expectedDoubleBacking.Clone();
        ApproxCatmullRom4Resampler.Resample(
            expectedDoubleBacking.AsSpan(0, 32),
            positions,
            levels,
            0.125,
            expectedDoubleBacking.AsSpan(4, OutputLength),
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            actualDoubleBacking.AsSpan(0, 32),
            positions,
            levels,
            0.125,
            actualDoubleBacking.AsSpan(4, OutputLength),
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(expectedDoubleBacking, actualDoubleBacking, "double source/double destination overlap");

        float[] expectedFloatBacking = Enumerable.Range(0, 48)
            .Select(index => (float)(2_000_000.0 + (100_000.0 * Math.Cos(index * 0.17))))
            .ToArray();
        float[] actualFloatBacking = (float[])expectedFloatBacking.Clone();
        ApproxCatmullRom4Resampler.Resample(
            expectedFloatBacking.AsSpan(0, 32),
            positions,
            levels,
            -0.125,
            expectedFloatBacking.AsSpan(5, OutputLength),
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            actualFloatBacking.AsSpan(0, 32),
            positions,
            levels,
            -0.125,
            actualFloatBacking.AsSpan(5, OutputLength),
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(expectedFloatBacking, actualFloatBacking, "float source/float destination overlap");

        double[] expectedCrossTypeBacking = Enumerable.Range(0, 40)
            .Select(index => 3_000_000.0 + (200_000.0 * Math.Sin(index * 0.11)))
            .ToArray();
        double[] actualCrossTypeBacking = (double[])expectedCrossTypeBacking.Clone();
        Span<float> expectedFloatDestination = MemoryMarshal.Cast<double, float>(
            expectedCrossTypeBacking.AsSpan()).Slice(8, OutputLength);
        Span<float> actualFloatDestination = MemoryMarshal.Cast<double, float>(
            actualCrossTypeBacking.AsSpan()).Slice(8, OutputLength);
        ApproxCatmullRom4Resampler.Resample(
            expectedCrossTypeBacking.AsSpan(0, 32),
            positions,
            levels,
            0.0625,
            expectedFloatDestination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            actualCrossTypeBacking.AsSpan(0, 32),
            positions,
            levels,
            0.0625,
            actualFloatDestination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(expectedCrossTypeBacking, actualCrossTypeBacking, "double source/float destination overlap");

        float[] expectedFloatToDoubleBacking = Enumerable.Range(0, 64)
            .Select(index => (float)(2_500_000.0 + (150_000.0 * Math.Cos(index * 0.07))))
            .ToArray();
        float[] actualFloatToDoubleBacking = (float[])expectedFloatToDoubleBacking.Clone();
        Span<double> expectedDoubleDestination = MemoryMarshal.Cast<float, double>(
            expectedFloatToDoubleBacking.AsSpan()).Slice(3, OutputLength);
        Span<double> actualDoubleDestination = MemoryMarshal.Cast<float, double>(
            actualFloatToDoubleBacking.AsSpan()).Slice(3, OutputLength);
        ApproxCatmullRom4Resampler.Resample(
            expectedFloatToDoubleBacking.AsSpan(0, 32),
            positions,
            levels,
            -0.0625,
            expectedDoubleDestination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            actualFloatToDoubleBacking.AsSpan(0, 32),
            positions,
            levels,
            -0.0625,
            actualDoubleDestination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(
            expectedFloatToDoubleBacking,
            actualFloatToDoubleBacking,
            "float source/double destination overlap");

        var converter = new VideoOutputConverter(
            ire0: 4_000_000.25,
            hzIre: 100_000.125,
            outputZero: 256,
            vsyncIre: -40.0,
            outputScale: 512.25);
        double[] expectedDoubleToUInt16Backing = Enumerable.Range(0, 40)
            .Select(index => 4_000_000.0 + (300_000.0 * Math.Sin(index * 0.13)))
            .ToArray();
        double[] actualDoubleToUInt16Backing = (double[])expectedDoubleToUInt16Backing.Clone();
        Span<ushort> expectedDoubleToUInt16Destination = MemoryMarshal.Cast<double, ushort>(
            expectedDoubleToUInt16Backing.AsSpan()).Slice(12, OutputLength);
        Span<ushort> actualDoubleToUInt16Destination = MemoryMarshal.Cast<double, ushort>(
            actualDoubleToUInt16Backing.AsSpan()).Slice(12, OutputLength);
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            expectedDoubleToUInt16Backing.AsSpan(0, 32),
            positions,
            levels,
            0.03125,
            converter,
            expectedDoubleToUInt16Destination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            actualDoubleToUInt16Backing.AsSpan(0, 32),
            positions,
            levels,
            0.03125,
            converter,
            actualDoubleToUInt16Destination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(
            expectedDoubleToUInt16Backing,
            actualDoubleToUInt16Backing,
            "double source/ushort destination overlap");

        float[] expectedFloatToUInt16Backing = Enumerable.Range(0, 48)
            .Select(index => (float)(4_000_000.0 + (300_000.0 * Math.Cos(index * 0.15))))
            .ToArray();
        float[] actualFloatToUInt16Backing = (float[])expectedFloatToUInt16Backing.Clone();
        Span<ushort> expectedFloatToUInt16Destination = MemoryMarshal.Cast<float, ushort>(
            expectedFloatToUInt16Backing.AsSpan()).Slice(8, OutputLength);
        Span<ushort> actualFloatToUInt16Destination = MemoryMarshal.Cast<float, ushort>(
            actualFloatToUInt16Backing.AsSpan()).Slice(8, OutputLength);
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            expectedFloatToUInt16Backing.AsSpan(0, 32),
            positions,
            levels,
            -0.03125,
            converter,
            expectedFloatToUInt16Destination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            actualFloatToUInt16Backing.AsSpan(0, 32),
            positions,
            levels,
            -0.03125,
            converter,
            actualFloatToUInt16Destination,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(
            expectedFloatToUInt16Backing,
            actualFloatToUInt16Backing,
            "float source/ushort destination overlap");

        double[] expectedPositionBacking = new double[OutputLength + 8];
        positions.CopyTo(expectedPositionBacking, 0);
        double[] actualPositionBacking = (double[])expectedPositionBacking.Clone();
        double[] separateSource = Enumerable.Range(0, 40)
            .Select(index => 1_500_000.0 + (250_000.0 * Math.Cos(index * 0.09)))
            .ToArray();
        ApproxCatmullRom4Resampler.Resample(
            separateSource,
            expectedPositionBacking.AsSpan(0, OutputLength),
            levels,
            -0.03125,
            expectedPositionBacking.AsSpan(4, OutputLength),
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            separateSource,
            actualPositionBacking.AsSpan(0, OutputLength),
            levels,
            -0.03125,
            actualPositionBacking.AsSpan(4, OutputLength),
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(expectedPositionBacking, actualPositionBacking, "position/destination overlap");
    }

    private static void AssertForcedModesMatch(
        double[] doubleSource,
        float[] floatSource,
        double[] positions,
        double[] levels,
        double sourcePositionShift,
        string scenario)
    {
        var scalarDoubleToFloat = new float[positions.Length];
        var vectorDoubleToFloat = new float[positions.Length];
        ApproxCatmullRom4Resampler.Resample(
            doubleSource,
            positions,
            levels,
            sourcePositionShift,
            scalarDoubleToFloat,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            doubleSource,
            positions,
            levels,
            sourcePositionShift,
            vectorDoubleToFloat,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(scalarDoubleToFloat, vectorDoubleToFloat, $"double->float, {scenario}");

        var scalarFloatToFloat = new float[positions.Length];
        var vectorFloatToFloat = new float[positions.Length];
        ApproxCatmullRom4Resampler.Resample(
            floatSource,
            positions,
            levels,
            sourcePositionShift,
            scalarFloatToFloat,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            floatSource,
            positions,
            levels,
            sourcePositionShift,
            vectorFloatToFloat,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(scalarFloatToFloat, vectorFloatToFloat, $"float->float, {scenario}");

        var scalarDoubleToDouble = new double[positions.Length];
        var vectorDoubleToDouble = new double[positions.Length];
        ApproxCatmullRom4Resampler.Resample(
            doubleSource,
            positions,
            levels,
            sourcePositionShift,
            scalarDoubleToDouble,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            doubleSource,
            positions,
            levels,
            sourcePositionShift,
            vectorDoubleToDouble,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(scalarDoubleToDouble, vectorDoubleToDouble, $"double->double, {scenario}");

        var scalarFloatToDouble = new double[positions.Length];
        var vectorFloatToDouble = new double[positions.Length];
        ApproxCatmullRom4Resampler.Resample(
            floatSource,
            positions,
            levels,
            sourcePositionShift,
            scalarFloatToDouble,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.Resample(
            floatSource,
            positions,
            levels,
            sourcePositionShift,
            vectorFloatToDouble,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(scalarFloatToDouble, vectorFloatToDouble, $"float->double, {scenario}");

        var converter = new VideoOutputConverter(
            ire0: 4_000_000.25,
            hzIre: 100_000.125,
            outputZero: 256,
            vsyncIre: -40.0,
            outputScale: 512.25);
        var scalarDoubleToUInt16 = new ushort[positions.Length];
        var vectorDoubleToUInt16 = new ushort[positions.Length];
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            doubleSource,
            positions,
            levels,
            sourcePositionShift,
            converter,
            scalarDoubleToUInt16,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            doubleSource,
            positions,
            levels,
            sourcePositionShift,
            converter,
            vectorDoubleToUInt16,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(scalarDoubleToUInt16, vectorDoubleToUInt16, $"double->ushort, {scenario}");

        var scalarFloatToUInt16 = new ushort[positions.Length];
        var vectorFloatToUInt16 = new ushort[positions.Length];
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            floatSource,
            positions,
            levels,
            sourcePositionShift,
            converter,
            scalarFloatToUInt16,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceScalar);
        ApproxCatmullRom4Resampler.ResampleToUInt16(
            floatSource,
            positions,
            levels,
            sourcePositionShift,
            converter,
            vectorFloatToUInt16,
            ApproxCatmullRom4Resampler.ExecutionMode.ForceVector);
        AssertBitwiseEqual(scalarFloatToUInt16, vectorFloatToUInt16, $"float->ushort, {scenario}");
    }

    private static void AssertBitwiseEqual<T>(T[] expected, T[] actual, string scenario)
        where T : unmanaged
    {
        Assert.True(
            MemoryMarshal.AsBytes(expected.AsSpan()).SequenceEqual(MemoryMarshal.AsBytes(actual.AsSpan())),
            $"Bitwise mismatch for {scenario}.");
    }

    [Fact(DisplayName = "Approx Catmull-Rom4 rejects invalid buffer shapes")]
    public void RejectsInvalidBufferShapes()
    {
        Assert.Throws<ArgumentException>(() =>
            ApproxCatmullRom4Resampler.Sample([1.0, 2.0, 3.0], 1.0));
        Assert.Throws<ArgumentException>(() =>
            ApproxCatmullRom4Resampler.Sample(new float[] { 1.0f, 2.0f, 3.0f }, 1.0));

        double[] source = [1.0, 2.0, 3.0, 4.0];
        Assert.Throws<ArgumentException>(() =>
            ApproxCatmullRom4Resampler.Resample(source, [1.0], [], new float[1]));
        Assert.Throws<ArgumentException>(() =>
            ApproxCatmullRom4Resampler.Resample(source, [1.0], [1.0], new float[2]));
        Assert.Throws<ArgumentNullException>(() =>
            ApproxCatmullRom4Resampler.ResampleToUInt16(source, [1.0], [1.0], null!, new ushort[1]));

        float[] floatSource = [1.0f, 2.0f, 3.0f, 4.0f];
        Assert.Throws<ArgumentException>(() =>
            ApproxCatmullRom4Resampler.Resample(floatSource, [1.0], [], new float[1]));
        Assert.Throws<ArgumentException>(() =>
            ApproxCatmullRom4Resampler.Resample(floatSource, [1.0], [1.0], new float[2]));
        Assert.Throws<ArgumentNullException>(() =>
            ApproxCatmullRom4Resampler.ResampleToUInt16(
                floatSource,
                [1.0],
                [1.0],
                null!,
                new ushort[1]));
    }
}
